"""add cascade

Revision ID: a2c43012bd76
Revises: 8a0b1864fecc
Create Date: 2024-12-22 02:57:21.018197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2c43012bd76'
down_revision: Union[str, None] = '8a0b1864fecc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_playlist_tracks_playlist_id_playlists', 'playlist_tracks', type_='foreignkey')
    op.create_foreign_key(op.f('fk_playlist_tracks_playlist_id_playlists'), 'playlist_tracks', 'playlists', ['playlist_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_playlist_tracks_playlist_id_playlists'), 'playlist_tracks', type_='foreignkey')
    op.create_foreign_key('fk_playlist_tracks_playlist_id_playlists', 'playlist_tracks', 'playlists', ['playlist_id'], ['id'])
    # ### end Alembic commands ###
