# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from services.user import user_pb2 as services_dot_user_dot_user__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in services/user/user_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UserStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUser = channel.unary_unary(
                '/user.User/GetUser',
                request_serializer=services_dot_user_dot_user__pb2.UserRequest.SerializeToString,
                response_deserializer=services_dot_user_dot_user__pb2.UserResponse.FromString,
                _registered_method=True)
        self.CreateUser = channel.unary_unary(
                '/user.User/CreateUser',
                request_serializer=services_dot_user_dot_user__pb2.CreateUserRequest.SerializeToString,
                response_deserializer=services_dot_user_dot_user__pb2.UserResponse.FromString,
                _registered_method=True)
        self.DeleteUser = channel.unary_unary(
                '/user.User/DeleteUser',
                request_serializer=services_dot_user_dot_user__pb2.UserRequest.SerializeToString,
                response_deserializer=services_dot_user_dot_user__pb2.UserResponse.FromString,
                _registered_method=True)
        self.GetUsers = channel.unary_unary(
                '/user.User/GetUsers',
                request_serializer=services_dot_user_dot_user__pb2.UsersRequest.SerializeToString,
                response_deserializer=services_dot_user_dot_user__pb2.UsersResponse.FromString,
                _registered_method=True)
        self.BindReferrer = channel.unary_unary(
                '/user.User/BindReferrer',
                request_serializer=services_dot_user_dot_user__pb2.BindReferrerRequest.SerializeToString,
                response_deserializer=services_dot_user_dot_user__pb2.BindReferrerResponse.FromString,
                _registered_method=True)
        self.GetReferrals = channel.unary_unary(
                '/user.User/GetReferrals',
                request_serializer=services_dot_user_dot_user__pb2.ReferralsRequest.SerializeToString,
                response_deserializer=services_dot_user_dot_user__pb2.UsersResponse.FromString,
                _registered_method=True)


class UserServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BindReferrer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReferrals(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUser,
                    request_deserializer=services_dot_user_dot_user__pb2.UserRequest.FromString,
                    response_serializer=services_dot_user_dot_user__pb2.UserResponse.SerializeToString,
            ),
            'CreateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUser,
                    request_deserializer=services_dot_user_dot_user__pb2.CreateUserRequest.FromString,
                    response_serializer=services_dot_user_dot_user__pb2.UserResponse.SerializeToString,
            ),
            'DeleteUser': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUser,
                    request_deserializer=services_dot_user_dot_user__pb2.UserRequest.FromString,
                    response_serializer=services_dot_user_dot_user__pb2.UserResponse.SerializeToString,
            ),
            'GetUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUsers,
                    request_deserializer=services_dot_user_dot_user__pb2.UsersRequest.FromString,
                    response_serializer=services_dot_user_dot_user__pb2.UsersResponse.SerializeToString,
            ),
            'BindReferrer': grpc.unary_unary_rpc_method_handler(
                    servicer.BindReferrer,
                    request_deserializer=services_dot_user_dot_user__pb2.BindReferrerRequest.FromString,
                    response_serializer=services_dot_user_dot_user__pb2.BindReferrerResponse.SerializeToString,
            ),
            'GetReferrals': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReferrals,
                    request_deserializer=services_dot_user_dot_user__pb2.ReferralsRequest.FromString,
                    response_serializer=services_dot_user_dot_user__pb2.UsersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'user.User', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('user.User', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class User(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.User/GetUser',
            services_dot_user_dot_user__pb2.UserRequest.SerializeToString,
            services_dot_user_dot_user__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.User/CreateUser',
            services_dot_user_dot_user__pb2.CreateUserRequest.SerializeToString,
            services_dot_user_dot_user__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.User/DeleteUser',
            services_dot_user_dot_user__pb2.UserRequest.SerializeToString,
            services_dot_user_dot_user__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.User/GetUsers',
            services_dot_user_dot_user__pb2.UsersRequest.SerializeToString,
            services_dot_user_dot_user__pb2.UsersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BindReferrer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.User/BindReferrer',
            services_dot_user_dot_user__pb2.BindReferrerRequest.SerializeToString,
            services_dot_user_dot_user__pb2.BindReferrerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetReferrals(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.User/GetReferrals',
            services_dot_user_dot_user__pb2.ReferralsRequest.SerializeToString,
            services_dot_user_dot_user__pb2.UsersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
