"""add authors

Revision ID: 00c746280f96
Revises: f62912b425fd
Create Date: 2024-12-14 20:13:38.251112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00c746280f96'
down_revision: Union[str, None] = 'f62912b425fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('track_authors',
    sa.Column('track_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], name=op.f('fk_track_authors_author_id_authors')),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], name=op.f('fk_track_authors_track_id_tracks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_track_authors')),
    sa.UniqueConstraint('track_id', 'author_id', name=op.f('uq_track_authors_track_id'))
    )
    op.drop_constraint('fk_tracks_author_id_authors', 'tracks', type_='foreignkey')
    op.drop_column('tracks', 'author_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('author_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('fk_tracks_author_id_authors', 'tracks', 'authors', ['author_id'], ['id'])
    op.drop_table('track_authors')
    # ### end Alembic commands ###
