"""add referrer id

Revision ID: 7e04efaa0a8f
Revises: 9f5a082d8bc6
Create Date: 2024-12-24 21:57:29.423808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e04efaa0a8f'
down_revision: Union[str, None] = '9f5a082d8bc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('referrer_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(op.f('fk_users_referrer_id_users'), 'users', 'users', ['referrer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_users_referrer_id_users'), 'users', type_='foreignkey')
    op.drop_column('users', 'referrer_id')
    # ### end Alembic commands ###
