# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: services/auth/auth.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'services/auth/auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18services/auth/auth.proto\x12\x04\x61uth\"$\n\x0fInitDataRequest\x12\x11\n\tinit_data\x18\x01 \x01(\t\"\x1a\n\x0cUserResponse\x12\n\n\x02id\x18\x01 \x01(\t2H\n\x04\x41uth\x12@\n\x11GetUserByInitData\x12\x15.auth.InitDataRequest\x1a\x12.auth.UserResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'services.auth.auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INITDATAREQUEST']._serialized_start=34
  _globals['_INITDATAREQUEST']._serialized_end=70
  _globals['_USERRESPONSE']._serialized_start=72
  _globals['_USERRESPONSE']._serialized_end=98
  _globals['_AUTH']._serialized_start=100
  _globals['_AUTH']._serialized_end=172
# @@protoc_insertion_point(module_scope)
