name: Build and Push Docker Images

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        service:
          - api-gateway
          - auth-service
          - pgsync
          - playlist-service
          - spotify-parser
          - track-service
          - user-service
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v3
      -
        name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          path: '${{ matrix.service }}'
      -
        name: Login to Docker Hub
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up QEMU
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:${{ matrix.service }}"
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/${{ matrix.service }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
