name: CI

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        service:
          - api-gateway
          - auth-service
          - playlist-service
          - spotify-parser
          - track-service
          - user-service
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v4
      -
        name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          path: '${{ matrix.service }}'
      -
        name: Ruff check
        uses: astral-sh/ruff-action@v2
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          src: "./${{ matrix.service }}/app"
  tests:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        service:
          - auth-service
          - playlist-service
          - track-service
          - user-service
    env:
      UV_SYSTEM_PYTHON: 1
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v4
      -
        name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          path: '${{ matrix.service }}'
      -
        uses: actions/setup-python@v5
        #if: steps.changed-files.outputs.any_changed == 'true'
        with:
          python-version: 3.12
      -
        name: Install uv
        uses: astral-sh/setup-uv@v5
        #if: steps.changed-files.outputs.any_changed == 'true'
        with:
          enable-cache: true
          cache-dependency-glob: "${{ matrix.service }}/requirements**.lock"
      -
        name: Install the project
        working-directory: ${{ matrix.service }}
        #if: steps.changed-files.outputs.any_changed == 'true'
        run: uv pip install -r requirements-dev.lock
      -
        name: run pytest
        working-directory: ${{ matrix.service }}
        run: python -m pytest tests